# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/rsa.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os
os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = "../platforms"
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(852, 419)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(310, 10, 191, 41))
        self.label.setBaseSize(QtCore.QSize(1, 1))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 100, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 180, 47, 13))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(420, 100, 61, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(420, 180, 47, 13))
        self.label_5.setObjectName("label_5")
        self.txtPlain = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txtPlain.setGeometry(QtCore.QRect(90, 100, 311, 71))
        self.txtPlain.setObjectName("txt_plain_text")
        self.txtCipher = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txtCipher.setGeometry(QtCore.QRect(90, 180, 311, 71))
        self.txtCipher.setObjectName("txt_cipher_text")
        self.txtSignature = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txtSignature.setGeometry(QtCore.QRect(480, 180, 311, 71))
        self.txtSignature.setObjectName("txt_sign")
        self.txtInformation = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txtInformation.setGeometry(QtCore.QRect(480, 100, 311, 71))
        self.txtInformation.setObjectName("txt_info")
        self.btnEn = QtWidgets.QPushButton(self.centralwidget)
        self.btnEn.setGeometry(QtCore.QRect(60, 310, 101, 31))
        self.btnEn.setObjectName("btn_encrypt")
        self.btnDe = QtWidgets.QPushButton(self.centralwidget)
        self.btnDe.setGeometry(QtCore.QRect(240, 310, 101, 31))
        self.btnDe.setObjectName("btn_decrypt")
        self.btnVe = QtWidgets.QPushButton(self.centralwidget)
        self.btnVe.setGeometry(QtCore.QRect(660, 310, 101, 31))
        self.btnVe.setObjectName("btn_verify")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(490, 310, 101, 31))
        self.pushButton_4.setObjectName("btn_sign")
        self.btnGen = QtWidgets.QPushButton(self.centralwidget)
        self.btnGen.setGeometry(QtCore.QRect(640, 60, 101, 31))
        self.btnGen.setObjectName("btn_gen_keys")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 852, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "RSA CIPHER"))
        self.label_2.setText(_translate("MainWindow", "Plain Text"))
        self.label_3.setText(_translate("MainWindow", "Cipher Text"))
        self.label_4.setText(_translate("MainWindow", "Information"))
        self.label_5.setText(_translate("MainWindow", "Signature"))
        self.btnEn.setText(_translate("MainWindow", "Encrypt"))
        self.btnDe.setText(_translate("MainWindow", "Decrypt"))
        self.btnVe.setText(_translate("MainWindow", "Verify"))
        self.pushButton_4.setText(_translate("MainWindow", "Sign"))
        self.btnGen.setText(_translate("MainWindow", "Generate Keys"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
